root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
  project:
    - "./tsconfig.json"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
rules:
  prettier/prettier:
    - error
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/explicit-member-accessibility": error
  "@typescript-eslint/member-ordering": warn
  camelcase: warn
  no-console: warn
  array-callback-return: error
  complexity:
    - warn
    - max: 15
  no-implicit-globals: warn
  require-await: warn
  no-shadow: warn
