root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: module
  project:
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
rules:
  prettier/prettier:
    - error
    - bracketSpacing: true
      singleQuote: false
      quoteProps: as-needed
      semi: true
      endOfLine: auto
      printWidth: 85
      trailingComma: none
      arrowParens: avoid

  '@typescript-eslint/no-namespace': off
  camelcase: warn
